routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('dashboard', function () {
    return view('Dashboard');
});

Route::get('list', function () {
    return view('list');
});



Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Addusers', 'MainController@viewAddUserForm')->name('adduser');
/*Route::get('/Addusers','MainController@addUserData');
*/Route::post('/addUserData','MainController@addUserData');
Route::post('/viewDashboard','MainController@viewDashboard');
Route::get('/show','MainController@viewDashboard');
Route::get('/deleteUser/{id}','MainController@deleteUserData');
Route::get('editblade','MainController@deleteUserData');

Route::get('/updateUser/{id}','MainController@updateUserData');
Route::post('/editUser','MainController@editUserData');
Route::get('/', 'Auth\LoginController@login');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('ajax-crud', 'AjaxCrudController');

Route::post('ajax-crud/update', 'AjaxCrudController@update')->name('ajax-crud.update');

Route::get('ajax-crud/destroy/{id}', 'AjaxCrudController@destroy');
/*Route::get('ajax-crud', 'AjaxCrudController@show');*/

Route::get('/getUsers', 'PagesController@getUsers');
Route::get('/addUser', 'PagesController@addUser');
Route::get('/updateUser', 'PagesController@updateUser');
Route::get('/deleteUser/{id}', 'PagesController@deleteUser');
Route::resource('crud','CrudsController');
/*Route::get('/calldashboardajax','MainController@callDashboardajax');
Route::get('/viewdashboardajax','MainController@viewDashboardajax');*/
Route::resource('ajax-posts', 'ajaxcrud\AjaxPostController');
//Route::get('preview-image-upload', 'AjaxPostController@index');
//Route::post('preview-image-upload', 'AjaxPostController@store');

resources/views/Addusers.blade.php
@extends('admin.layout.master')
@section('section')

  <center>
      <h2>Registration Form </h2>

    {{ Form::open(array('url' => url('/addUserData'), 'class'=>'reg-form')) }}
    {{ csrf_field() }}
    <div class="form-group">
     <label>Enter FirstName</label>
     <input type="text" name="firstName" class="form-control" />
    </div>
     <div class="form-group">
     <label>Enter LastName</label>
     <input type="text" name="lastName" class="form-control" />
    </div>
     <div class="form-group">
      <input type="radio" name="gender" value="female"> Female<br>
     
    </div>
     <div class="form-group">
     <label>Enter EmailAddress</label>
     <input type="email" name="email" class="form-control" />
    </div>
    <div class="form-group">
     <label>Enter Password</label>
     <input type="password" name="password" class="form-control" />
    </div>
    <div class="form-group">
      <input type="file" name="profileimage" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
  </div>
    <div class="form-group">
     <input type="submit" name="submit" class="btn btn-primary" value="submit" />
    </div>
       {!! Form::close() !!}

   </center>

@endsection

resources/views/Dashboard.blade.php
@extends('admin.layout.master')
@section('section')
   
<br><br>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title"> <center>View All Users</center></h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table" border="1px solid black">
                    <thead class=" text-primary">
                     <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Id
                      </th>
                      <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        First Name
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Last Name
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Gender
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Email
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Image
                      </th>
                      <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Password
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                        Edit
                      </th>
                       <th bgcolor="#28a74569" style="color: white;border: 1px solid black">
                       Delete
                      </th>
                    </thead>
                    <tbody style="background-color: #ffb6c178;">

                     @foreach($data as $value) 
                      <tr style="border: 1px solid black">
                        <td style="border: 1px solid black">
                         {{ $value->id }}
                        </td>
                        <td style="border: 1px solid black">
                          {{ $value->first_name }}
                        </td>
                        <td style="border: 1px solid black">
                          {{ $value->last_name }}
                        </td>
                         <td style="border: 1px solid black">
                          {{ $value->gender }}
                        </td >
                        <td style="border: 1px solid black">
                          {{ $value->email }}
                        </td>
                         <td style="border: 1px solid black">
                          <img src="{{asset('upload/'.$value->profileImage) }}">
                        </td>
                        <td style="border: 1px solid black">
                          {{ $value->password }}
                        </td>
                        <td style="border: 1px solid black">

                       <a href="/updateUser/{{ $value->id }}">    <button type="button" class="btn btn-info">Edit</button></a>

                        </td>
                        <td style="border: 1px solid black">
                       <a href="/deleteUser/{{ $value->id}}">   <button type="button" class="btn btn-warning">Delete</button></a>
                        </td>

                      </tr>
                      @endforeach

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>

    
  @endsection

resources/views/ajax_index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<style type="text/css"></style>

<body class="">
 
</div>
  <div class="wrapper ">
  <h3 style="text-align: center;"> All Users </h3>
    <div class="sidebar" data-color="orange">
     <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
              document.getElementById('logout-form').submit();">
     <i class="now-ui-icons education_atom"></i>
     <p style="float: right;">Logout</p></a>
     <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
     @csrf
     </form>
     </div>
     </div>
     <br>
     <br>
 <div class="container">    
     <div align="right">
      <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Create User</button>
     </div>
     <br />
   <div class="table-responsive">
    <table class="table table-bordered table-striped" id="user_table">
           <thead>
            <tr>
                <th width="10%">Image</th>
                <th width="35%">First Name</th>
                <th width="35%">Last Name</th>
                 <th width="35%">Email</th>
                 <th width="35%">Password</th>
            
                 <th width="30%">Action</th>
            </tr>
           </thead>
       </table>
   </div>
   <br />
   <br />
  </div>
 <div id="formModal" class="modal fade" role="dialog">
 <div class="modal-dialog">
  <div class="modal-content">
   <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add New User</h4>
        </div>
        <div class="modal-body">
         <span id="form_result"></span>
         <form method="post" id="sample_form" class="form-horizontal" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
            <label class="control-label col-md-4" >First Name : </label>
            <div class="col-md-8">
             <input type="text" name="first_name" id="first_name" class="form-control" />
            </div>
           </div>
           <div class="form-group">
            <label class="control-label col-md-4">Last Name : </label>
            <div class="col-md-8">
             <input type="text" name="last_name" id="last_name" class="form-control" />
            </div>
           </div>
            <div class="form-group">
            <label class="control-label col-md-4">Email : </label>
            <div class="col-md-8">
             <input type="text" name="email" id="email" class="form-control" />
            </div>
           </div>
             <div class="form-group">
            <label class="control-label col-md-4">Password : </label>
            <div class="col-md-8">
             <input type="Password" name="last_name2" id="last_name2" class="form-control" />
            </div>
           </div>
       
        
           <div class="form-group">
            <label class="control-label col-md-4">Select Profile Image : </label>
            <div class="col-md-8">
             <input type="file" name="image" id="image" />
             <span id="store_image"></span>
            </div>
           </div>
           <br />
           <div class="form-group" align="center">
            <input type="hidden" name="action" id="action" />
            <input type="hidden" name="hidden_id" id="hidden_id" />
            <input type="submit" name="action_button" id="action_button" class="btn btn-warning" value="Add" />
           </div>
         </form>
        </div>
     </div>
    </div>
</div>

<div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Confirmation</h2>
            </div>
            <div class="modal-body">
                <h4 align="center" style="margin:0;">Are you sure you want to remove this user?</h4>
            </div>
            <div class="modal-footer">
             <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>


<script>
$(document).ready(function(){

 $('#user_table').DataTable({
  processing: true,
  serverSide: true,
  ajax:{
   url: "{{ route('ajax-crud.index') }}",
  },
  columns:[
   {
    data: 'image',
    name: 'image',
    render: function(data, type, full, meta){
     return "<img src={{ URL::to('/') }}/images/" + data + " width='70' class='img-thumbnail' />";
    },
    orderable: false
   },
   {
    data: 'first_name',
    name: 'first_name'
   },
   {
    data: 'last_name',
    name: 'last_name'
   },
  {
    data: 'email',
    name: 'email'
   },
    {
    data: 'last_name2',
    name: 'last_name2'
   },
  
   {
    data: 'action',
    name: 'action',
    orderable: false
   }
  ]
 });

 $('#create_record').click(function(){
  $('.modal-title').text("Add New User");
     $('#action_button').val("Add");
     $('#action').val("Add");
     $('#formModal').modal('show');
 });

 $('#sample_form').on('submit', function(event){
  event.preventDefault();
  if($('#action').val() == 'Add')
  {
   $.ajax({
    url:"{{ route('ajax-crud.store') }}",
    method:"POST",
    data: new FormData(this),
    contentType: false,
    cache:false,
    processData: false,
    dataType:"json",
    success:function(data)
    {
     var html = '';
     if(data.errors)
     {
      html = '<div class="alert alert-danger">';
      for(var count = 0; count < data.errors.length; count++)
      {
       html += '<p>' + data.errors[count] + '</p>';
      }
      html += '</div>';
     }
     if(data.success)
     {
      html = '<div class="alert alert-success">' + data.success + '</div>';
      $('#sample_form')[0].reset();
      $('#user_table').DataTable().ajax.reload();
     }
     $('#form_result').html(html);
    }
   })
  }

  if($('#action').val() == "Edit")
  {
   $.ajax({
    url:"{{ route('ajax-crud.update') }}",
    method:"POST",
    data:new FormData(this),
    contentType: false,
    cache: false,
    processData: false,
    dataType:"json",
    success:function(data)
    {
     var html = '';
     if(data.errors)
     {
      html = '<div class="alert alert-danger">';
      for(var count = 0; count < data.errors.length; count++)
      {
       html += '<p>' + data.errors[count] + '</p>';
      }
      html += '</div>';
     }
     if(data.success)
     {
      html = '<div class="alert alert-success">' + data.success + '</div>';
      $('#sample_form')[0].reset();
      $('#store_image').html('');
      $('#user_table').DataTable().ajax.reload();
     }
     $('#form_result').html(html);
    }
   });
  }
 });

 $(document).on('click', '.edit', function(){
  var id = $(this).attr('id');
  $('#form_result').html('');
  $.ajax({
   url:"/ajax-crud/"+id+"/edit",
   dataType:"json",
   success:function(html){
    $('#first_name').val(html.data.first_name);
    $('#last_name').val(html.data.last_name);
    $('#email').val(html.data.email);
    $('#last_name2').val(html.data.last_name2);
   
    $('#store_image').html("<img src={{ URL::to('/') }}/images/" + html.data.image + " width='70' class='img-thumbnail' />");
    $('#store_image').append("<input type='hidden' name='hidden_image' value='"+html.data.image+"' />");
    $('#hidden_id').val(html.data.id);
    $('.modal-title').text("Edit New User");
    $('#action_button').val("Edit");
    $('#action').val("Edit");
    $('#formModal').modal('show');
   }
  })
 });

 var user_id;

 $(document).on('click', '.delete', function(){
  user_id = $(this).attr('id');
  $('#confirmModal').modal('show');
 });

 $('#ok_button').click(function(){
  $.ajax({
   url:"ajax-crud/destroy/"+user_id,
   beforeSend:function(){
    $('#ok_button').text('Deleting...');
   },
   success:function(data)
   {
    setTimeout(function(){
     $('#confirmModal').modal('hide');
     $('#user_table').DataTable().ajax.reload();
    }, 2000);
   }
  })
 });

});
</script>

resources/views/create.blade.php
@extends('parent')

@section('main')
@if($errors->any())
<div class="alert alert-danger">
 <ul>
  @foreach($errors->all() as $error)
  <li>{{ $error }}</li>
  @endforeach
 </ul>
</div>
@endif
<div align="right">
 <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
</div>

<form method="post" action="{{ route('crud.store') }}" enctype="multipart/form-data">

 @csrf
 <div class="form-group">
  <label class="col-md-4 text-right">Enter First Name</label>
  <div class="col-md-8">
   <input type="text" name="first_name" class="form-control input-lg" />
  </div>
 </div>
 <br />
 <br />
 <br />
 <div class="form-group">
  <label class="col-md-4 text-right">Enter Last Name</label>
  <div class="col-md-8">
   <input type="text" name="last_name" class="form-control input-lg" />
  </div>
 </div>
 <br />
 <br />
 <br />
 <div class="form-group">
  <label class="col-md-4 text-right">Select Profile Image</label>
  <div class="col-md-8">
   <input type="file" name="image" />
  </div>
 </div>
 <br /><br /><br />
 <div class="form-group text-center">
  <input type="submit" name="add" class="btn btn-primary input-lg" value="Add" />
 </div>

</form>

@endsection

resources/views/edit.blade.php
@extends('parent')

@section('main')
            
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div align="right">
                <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
            </div>
            <br />
     <form method="post" action="{{ route('crud.update', $data->id) }}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
      <div class="form-group">
       <label class="col-md-4 text-right">Enter First Name</label>
       <div class="col-md-8">
        <input type="text" name="first_name" value="{{ $data->first_name }}" class="form-control input-lg" />
       </div>
      </div>
      <br />
      <br />
      <br />
      <div class="form-group">
       <label class="col-md-4 text-right">Enter Last Name</label>
       <div class="col-md-8">
        <input type="text" name="last_name" value="{{ $data->last_name }}" class="form-control input-lg" />
       </div>
      </div>
      <br />
      <br />
      <br />
      <div class="form-group">
       <label class="col-md-4 text-right">Select Profile Image</label>
       <div class="col-md-8">
        <input type="file" name="image" />
              <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" width="100" />
                        <input type="hidden" name="hidden_image" value="{{ $data->image }}" />
       </div>
      </div>
      <br /><br /><br />
      <div class="form-group text-center">
       <input type="submit" name="edit" class="btn btn-primary input-lg" value="Edit" />
      </div>
     </form>

@endsection

resources/views/editUser.blade.php
@extends('admin.layout.master')
@section('section')
<link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="../../assets/css/now-ui-dashboard.css?v=1.5.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="../../assets/demo/demo.css" rel="stylesheet" />
<center>
      {{ Form::open(array('url' => url('/editUser'), 'class'=>'reg-form','files'=>true)) }}

      <table width="50%">
        <tbody><h2><strong>Edit User</strong></h2>
          <tr>
            <td class="py-4">{!! Form::label('Id', '' , array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::text('id', $data->id, array('class' => 'form-control bg-white')) !!}</td>
          </tr>
          <tr>
            <td class="py-4">{!! Form::label('Fist Name', '' , array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::text('firstName', $data->first_name, array('class' => 'form-control bg-white')) !!}</td>
          </tr>
          <tr>
            <td class="py-4">{!! Form::label('Last Name', '' , array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::text('lastName',$data->last_name , array('class' => 'form-control bg-white')) !!}</td>
          </tr>

          <tr>
           <td class="py-4">{!! Form::label('Select gender','', array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::radio('gender', 'male') !!} male &nbsp;  {!! Form::radio('gender', 'female') !!}  female</td>
          </tr>
          <tr>
            <td class="py-4">{!! Form::label('Email', '' , array('class'=>'form-lable')) !!}</td>
            <td  class="py-4">{!! Form::email('email', $data->email,array('class' => 'form-control bg-white')) !!}</td>
          </tr>

           <tr>
            <td>{!! Form::label('Status', '' , array('class'=>'form-lable')) !!}</td>
            <td>{!! Form::select('status', array('Active' => 'Active', 'Deactive' => 'Deactive')) !!}</td>
          </tr>
          <tr>
            <td class="py-4">{!! Form::label('Profile Image', '' , array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::file('profileImage') !!}</td>
          </tr>

          <tr>
            <td class="py-4">{!! Form::label('Password', '' , array('class'=>'form-lable')) !!}</td>
            <td class="py-4">{!! Form::password('password'); !!}</td>
          </tr>
          <tr><td>{!! Form::submit('UPDATE',array('class'=>'btn btn-primary')) !!}</td></tr>

        </tbody>
      </table>
     </center>      

      {!! Form::close() !!}
@endsection

resources/views/home.blade.php
@extends('admin.layout.content')
@section('section')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/lists.blade.php
@extends('admin.layout.master')
@section('title','Dashboard')
@section('content')


      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title"> User Info</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                     <th>
                        Id
                      </th>
                      <th>
                        First Name
                      </th>
                       <th>
                        Last Name
                      </th>
                       <th>
                        Gender
                      </th>
                       <th>
                        Email
                      </th>
                      <th>
                        Status
                      </th>
                       <th>
                        Image
                      </th>
                      <th>
                        Password
                      </th>
                       <th>
                        UPDATE
                      </th>
                       <th>
                       DELETE
                      </th>
                    </thead>
                    <tbody>
                     @foreach($data as $value) 
                      <tr>
                        <td>
                         {{ $value->id }}
                        </td>
                        <td>
                          {{ $value->first_name }}
                        </td>
                        <td>
                          {{ $value->last_name }}
                        </td>
                         <td>
                          {{ $value->gender }}
                        </td>
                        <td>
                          {{ $value->email }}
                        </td>
                        <td>
                          {{ $value->status }}
                        </td>
                         <td>
                          {{ $value->profileImage }}
                        </td>
                        <td>
                          {{ $value->password }}
                        </td>
                        <td>
                       <a href="/updateUser/{{ $value->id }}">  <button type="button" class="btn btn-info">UPDATE</button></a>

                        </td>
                        <td>
                       <a href="/deleteUser/{{ $value->id}}">   <button type="button" class="btn btn-warning">DELETE</button></a>
                        </td>

                      </tr>
                      @endforeach

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
@endsection

resources/views/login.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Login') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('login') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/myform.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel Dependent Dropdown Example with demo</title>
    <script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>
    <link rel="stylesheet" href="http://demo.itsolutionstuff.com/plugin/bootstrap-3.min.css">
</head>
<body>


<div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">Select State and get bellow Related City</div>
      <div class="panel-body">
            <div class="form-group">
                <label for="title">Select State:</label>
                <select name="state" class="form-control" style="width:350px">
                    <option value="">--- Select State ---</option>
                    @foreach ($states as $key => $value)
                        <option value="{{ $key }}">{{ $value }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="title">Select City:</label>
                <select name="city" class="form-control" style="width:350px">
                </select>
            </div>
      </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        $('select[name="state"]').on('change', function() {
            var stateID = $(this).val();
            if(stateID) {
                $.ajax({
                    url: '/myform/ajax/'+stateID,
                    type: "GET",
                    dataType: "json",
                    success:function(data) {

                        
                        $('select[name="city"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="city"]').append('<option value="'+ key +'">'+ value +'</option>');
                        });


                    }
                });
            }else{
                $('select[name="city"]').empty();
            }
        });
    });
</script>


</body>
</html>

resources/views/view.blade.php
@extends('parent')

@section('main')

<div class="jumbotron text-center">
 <div align="right">
  <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
 </div>
 <br />
 <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" />
 <h3>First Name - {{ $data->first_name }} </h3>
 <h3>Last Name - {{ $data->last_name }}</h3>
</div>
@endsection